mysql_host: 192.168.42.157
mysql_database: agama
mysql_user: agama
mysql_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31643162663433663462653736643766613432623435303361393335383538313432313932656466
          6236633031666465363535376536323666393735373737310a356535643933383262613331393665
          38656638373166303065656637633561646464323364323861366339343164373338663634336239
          3039356664313766300a646531663731376463363463653136343032636264303637636563383132
          6632

dns_forwarders:
  - 8.8.8.8
  - 8.8.4.4

allowed_networks:
  - 192.168.42.0/24
  - 127.0.0.0/8

domain: nuttn.go.
