---
  - name: MySQL user
    mysql_user:
      name: "{{ mysql_backup_user }}"
      password: "{{ mysql_backup_password }}"
      state: present
      priv: "{{ mysql_database }}.*:ALL"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: True

  - name: configure mysqldump
    template:
      src: my.cnf.j2
      dest: /home/backup/.my.cnf
      owner: backup
      mode: '0600'
