---
  - name: Setup
    hosts: all
    tasks:
      - setup:

  - name: Node exporter
    hosts: all
    become: yes
    roles:
      - node_exporter

  - name: Prometheus
    hosts: prometheus_server
    become: yes
    roles:
      - prometheus
