---
  - name: Get binary
    unarchive:
      src: https://github.com/cafebazaar/keepalived-exporter/releases/download/v1.1.0/keepalived-exporter-1.1.0.linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes
      extra_opts: [--strip-components=1]




  - name: Create Service
    template:
      src: prometheus-keepalived-exporter.service.j2
      dest: /etc/systemd/system/prometheus-keepalived-exporter.service
    notify:
      - systemctl daemon-reload
      - restart keepalive exporter
