---
  - name: Package
    apt:
      name: prometheus-mysqld-exporter
      state: present
      update_cache: yes

  - name: Config
    template:
      src: my.cnf.j2
      dest: /var/lib/prometheus/.my.cnf
    notify:
      - restart mysql_exporter

  - name: MySQL user
    mysql_user:
      name: "{{ mysql_exporter_user }}"
      password: "{{ mysql_exporter_password }}"
      state: present
      priv: "*.*:PROCESS,REPLICATION CLIENT,SELECT"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    no_log: True

  - name: Enabled
    service:
      name: prometheus-mysqld-exporter
      state: started
      enabled: yes
