- name: install MySQL
  apt:
    name: mysql-server
    state: present
    

- name: MySQL config override
  template:
    src: override.cnf.j2
    dest: /etc/mysql/mysql.conf.d/override.cnf
  notify: restart mysql

- name: install PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    state: present
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: True

- name: replication user
  mysql_user:
    name: "{{ mysql_replication_user }}"
    password: "{{ mysql_replication_password }}"
    state: present
    priv: "*.*:REPLICATION SLAVE"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: True
