- name: install MySQL
  apt:
    name: mysql-server
    state: present
    update_cache: yes

- name: MySQL config override
  copy:
    src: override.cnf
    dest: /etc/mysql/mysql.conf.d/
    mode: 644
  notify: restart mysql

- name: install PyMySQL
  apt:
    name: python3-pymysql
    state: present

- name: MySQL database
  mysql_db:
    name: "{{ mysql_database }}"
    login_unix_socket: /var/run/mysqld/mysqld.sock

- name: MySQL user
  mysql_user:
    name: "{{ mysql_user }}"
    password: "{{ mysql_password }}"
    state: present
    priv: "{{ mysql_database }}.*:ALL"
    host: "%"
    login_unix_socket: /var/run/mysqld/mysqld.sock
  no_log: True
