---
  - name: Package
    apt:
      name: prometheus-bind-exporter
      state: present
      update_cache: yes

  - name: start
    service:
      name: prometheus-bind-exporter
      state: restarted
