---
  - name: Setup
    hosts: all
    tasks:
      - setup:

  - name: Node exporter
    hosts: all
    become: yes
    roles:
      - node_exporter
      - reverse_proxy

  - name: Prometheus
    hosts: prometheus
    become: yes
    roles:
      - prometheus
