---
  - name: Exporter
    docker_container:
      name: haproxy_exporter
      image: quay.io/prometheus/haproxy-exporter:v0.9.0
      restart_policy: unless-stopped
      ports:
        - 9101:9101
      command: --haproxy.scrape-uri="http://172.17.0.1:88/haproxy?stats;csv"
