---
  - name: haproxy exporter container
    docker_container:
      name: haproxy_exporter
      image: quay.io/prometheus/haproxy-exporter:v0.12.0
      ports: 9101:9101
      command: --haproxy.scrape-uri="http://172.17.0.1:88/haproxy?stats;csv"
