---
  - name: Get binary
    unarchive:
      src: https://github.com/nginxinc/nginx-prometheus-exporter/releases/download/v0.8.0/nginx-prometheus-exporter-0.8.0-linux-amd64.tar.gz
      dest: /usr/local/bin
      remote_src: yes

  - name: Expose metrics on nginx
    template:
      src: stub_status.j2
      dest: /etc/nginx/sites-enabled/stub_status
    notify: restart nginx

  - name: Create Service
    template:
      src: prometheus-nginx-exporter.service.j2
      dest: /etc/systemd/system/prometheus-nginx-exporter.service
    notify:
      - systemctl daemon-reload
      - restart nginx exporter
